### ISSUE TITLE
Forget my slack 

### ISSUE THREAD

**Issue by Coelancanth** [ItsDaSpecialK/IN0037-Group-23#4]
Hi, sorry for not participating in last exercise, (i was hospitalized and my computer was broken... ) 

So, maybe someone could send me slack address so that we can stay in touch?

**Comment by Formicarufa** [comment]
in0037.slack.com/

**Comment by Coelancanth** [comment]
can you reinvite me? i forgot my email address....

haoran.chen@tum.de

thanks
